version: '3'
services:
    server:
        build:
            context: ./Server
            dockerfile: Dockerfile
        depends_on:
            - nameserver
        deploy:
            replicas: 2
    nameserver:
        build:
            context: ./Nameserver
            dockerfile: Dockerfile
    client:
        build:
            context: ./Client
            dockerfile: Dockerfile
        depends_on:
            - server
