version: '3'
services:
    server:
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - nameserver
        deploy:
            replicas: 2
    nameserver:
        build:
            context: ./
            dockerfile: Dockerfile2
    client:
        build:
            context: ./
            dockerfile: Dockerfile3
        depends_on:
            - server
