version: '3'
services:
    server:

        image:
            leosimonetti/ds_2_project:storage_server
        depends_on:
            - nameserver
        deploy:
            replicas: 5
    nameserver:
        image:
            leosimonetti/ds_2_project:name_server
    client:
        image:
            leosimonetti/ds_2_project:client
        depends_on:
            - server
